### ISSUE TITLE
ClassNotFoundException: com.miui.referrer.api.GetAppsReferrerStateListener

### ISSUE THREAD

**Issue by Turnsole** [mParticle/mparticle-android-sdk#261]
Here's the stacktrace: 

```
Caused by: java.lang.ClassNotFoundException: com.miui.referrer.api.GetAppsReferrerStateListener
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:189)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:147)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$loadClass$0(SandboxClassLoader.java:133)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.loadClass(SandboxClassLoader.java:133)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.appsflyer.internal.AFb1xSDK.init(:835)
	at com.mparticle.kits.AppsFlyerKit.onKitCreate(AppsFlyerKit.kt:48)
	at com.mparticle.kits.KitManagerImpl.initializeKit(KitManagerImpl.java:266)
	at com.mparticle.kits.KitManagerImpl.configureKits(KitManagerImpl.java:226)
	at com.mparticle.kits.KitManagerImpl.lambda$updateKits$0(KitManagerImpl.java:157)
	at android.os.Handler.$$robo$$android_os_Handler$handleCallback(Handler.java:751)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.$$robo$$android_os_Handler$dispatchMessage(Handler.java:95)
	at android.os.Handler.dispatchMessage(Handler.java)
```

This is showing up for `com.mparticle:android-appsflyer-kit:5.47.0` but not `5.45.0`.  No events are getting sent to Appsflyer in my integration, but they are with `5.45.0`.

**Comment by mchuangatmp** [comment]
We opened a ticket and it's being tracked internally as SQDSDKS-4688.  Please reach out to your mParticle account manager to escalate if this is an urgent issue.

**Comment by Turnsole** [comment]
Anecdotally, I no longer see this issue in `5.48.1`.

**Comment by mchuangatmp** [comment]
We did make some fixes to support Android 13 recently.  Since things are working as expected in the newest SDK version,  I'll close this ticket.  Please reach out to your mParticle account manager and open a ticket if you run into further issues
