### ISSUE TITLE
 v5.48.2: NullPointerException crashes

### ISSUE THREAD

**Issue by chad-cmb** [mParticle/mparticle-android-sdk#285]
Prior to upgrading to 5.48.2 - we did not see these crashes. Immediately upon deployment, we see nearly 2,000 crashes when users are launching the application.  It says the app crashes within 1 second of launch and our methods are not in the stack at all. 

<img width="1237" alt="Screen Shot 2022-11-28 at 1 08 02 PM" src="https://user-images.githubusercontent.com/92877129/204360436-fe7ece58-c8d7-4b5a-86c2-0e1524ce9834.png">
---
<img width="477" alt="Screen Shot 2022-11-28 at 1 10 28 PM" src="https://user-images.githubusercontent.com/92877129/204360905-8af2740c-416f-48c7-8933-95c419e00115.png">

--------------
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
       at com.mparticle.kits.FilteredMParticleUser$1.onUserAttributesReceived(FilteredMParticleUser.java:87)
       at com.mparticle.r0.a(SourceFile:25)
       at com.mparticle.d0$a$a.run(SourceFile:1)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:359)
       at android.app.ActivityThread.main(ActivityThread.java:7418)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by mchuangatmp** [comment]
@chad-cmb we just released a fix for this in v5.48.3, I'm going to close this ticket now.  Please contact mParticle support if there are further issues
