### ISSUE TITLE
Branch - Fatal Exception: java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by perrotj** [mParticle/mparticle-android-sdk#30]
I have mParticle **5.6.0** and Branch kit **2.16.0**, I saw this crash in Crashlytics for one of our users:

`Fatal Exception: java.lang.NoSuchFieldError: No field NONE of type Lcom/mparticle/MParticle$LogLevel; in class Lcom/mparticle/MParticle$LogLevel; or its superclasses (declaration of 'com.mparticle.MParticle$LogLevel' appears in /data/app/com.xxx.xxx-2/base.apk)
       at com.mparticle.kits.BranchMetricsKit.onKitCreate(BranchMetricsKit.java:60)
       at com.mparticle.kits.KitManagerImpl.initializeKit(KitManagerImpl.java:212)
       at com.mparticle.kits.KitManagerImpl.configureKits(KitManagerImpl.java:174)
       at com.mparticle.kits.KitManagerImpl$UpdateKitRunnable.run(KitManagerImpl.java:131)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

**Comment by samdozor** [comment]
Hi @perrotj are you still having this issue? This looks like it could be a proguard related failure. `LogLevel` should be a publicly accessible class.

**Comment by perrotj** [comment]
No, and this was happening on a very old device. I'll close the issue.
