### ISSUE TITLE
mParticle NoClassDefFoundError

### ISSUE THREAD

**Issue by hussein-yassine** [mParticle/mparticle-android-sdk#306]
Hello

As Crashlytics shows, a recurring crash occurring in the **background** on a **Xiaomi Mi A1 device** and below are the available information:

SDK: MParticle dependency version: 5.39.0
Device Platform: Android
Device Platform OS Version: Android 9
Device Model: Xiaomi Mi A1 device

Crash Stacktrace:
`Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:354)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)`

`Caused by java.lang.NoClassDefFoundError: com.google.firebase.perf.v1.NetworkRequestMetric$CustomAttributesDefaultEntryHolder
       at com.google.firebase.perf.v1.NetworkRequestMetric.dynamicMethod(NetworkRequestMetric.java:2411)
       at com.google.protobuf.GeneratedMessageLite.dynamicMethod(GeneratedMessageLite.java:256)
       at com.google.protobuf.GeneratedMessageLite.buildMessageInfo(GeneratedMessageLite.java:286)
       at com.google.protobuf.GeneratedMessageInfoFactory.messageInfoFor(GeneratedMessageInfoFactory.java:60)
       at com.google.protobuf.ManifestSchemaFactory$CompositeMessageInfoFactory.messageInfoFor(ManifestSchemaFactory.java:143)
       at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:55)
       at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:90)
       at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:104)
       at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:175)
       at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:397)
       at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:405)
       at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.build(NetworkRequestMetricBuilder.java:321)
       at com.google.firebase.perf.network.InstrURLConnectionBase.disconnect(InstrURLConnectionBase.java:80)
       at com.google.firebase.perf.network.InstrHttpsURLConnection.disconnect(InstrHttpsURLConnection.java:63)
       at io.branch.referral.network.BranchRemoteInterfaceUrlConnection.doRestfulPost(BranchRemoteInterfaceUrlConnection.java:250)
       at io.branch.referral.network.BranchRemoteInterfaceUrlConnection.doRestfulPost(BranchRemoteInterfaceUrlConnection.java:49)
       at io.branch.referral.network.BranchRemoteInterface.make_restful_post(BranchRemoteInterface.java:137)
       at io.branch.referral.Branch$BranchPostTask.doInBackground(Branch.java:2205)
       at io.branch.referral.Branch$BranchPostTask.doInBackground(Branch.java:2175)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)`

`Caused by java.lang.VerifyError: Verifier rejected class com.google.protobuf.ByteString: com.google.protobuf.ByteString com.google.protobuf.ByteString.j(java.io.InputStream, int): [0xFFFFFFFF] wide register index out of range (16494+1 >= 7) (declaration of 'com.google.protobuf.ByteString' appears in base.apk!classes3.dex)
       at com.google.protobuf.WireFormat$JavaType.<clinit>(WireFormat.java:91)
       at com.google.protobuf.WireFormat$FieldType.<clinit>(WireFormat.java:112)
       at com.google.firebase.perf.v1.NetworkRequestMetric$CustomAttributesDefaultEntryHolder.<clinit>(NetworkRequestMetric.java:969)
       at com.google.firebase.perf.v1.NetworkRequestMetric.dynamicMethod(NetworkRequestMetric.java:2411)
       at com.google.protobuf.GeneratedMessageLite.dynamicMethod(GeneratedMessageLite.java:256)
       at com.google.protobuf.GeneratedMessageLite.buildMessageInfo(GeneratedMessageLite.java:286)
       at com.google.protobuf.GeneratedMessageInfoFactory.messageInfoFor(GeneratedMessageInfoFactory.java:60)
       at com.google.protobuf.ManifestSchemaFactory$CompositeMessageInfoFactory.messageInfoFor(ManifestSchemaFactory.java:143)
       at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:55)
       at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:90)
       at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:104)
       at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:175)
       at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:397)
       at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:405)
       at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.build(NetworkRequestMetricBuilder.java:321)
       at com.google.firebase.perf.network.InstrHttpInputStream.read(InstrHttpInputStream.java:130)
       at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
       at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:351)
       at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:180)
       at java.io.InputStreamReader.read(InputStreamReader.java:184)
       at java.io.BufferedReader.fill(BufferedReader.java:172)
       at java.io.BufferedReader.readLine(BufferedReader.java:335)
       at java.io.BufferedReader.readLine(BufferedReader.java:400)
       at com.mparticle.internal.MPUtility.getJsonResponse(MPUtility.java:13)
       at com.mparticle.internal.MPUtility.getJsonResponse(MPUtility.java:1)
       at com.mparticle.internal.g.a(g.java:48)
       at com.mparticle.internal.o.a(o.java:16)
       at com.mparticle.b.handleMessage(b.java:17)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:65)`

![crash trace 1](https://user-images.githubusercontent.com/50947162/212635956-9a8c7642-91c1-4b66-ba2f-225931a6ed4d.PNG)
[stacktrace.txt](https://github.com/mParticle/mparticle-android-sdk/files/10423987/stacktrace.txt)

**Comment by samdozor** [comment]
This looks like be a crash in the Firebase SDK, which it appears you are using for network performance measurement. The mP SDK is in the stack trace since the Firebase SDK is attempting to intercept our HTTP requests. Closing this as it would be an issue with the Firebase SDK.
