### ISSUE TITLE
Android ANR

### ISSUE THREAD

**Issue by ExpensiveBelly** [mParticle/mparticle-android-sdk#310]
Sony Xperia 10 III

```
mParticleMessageHandler (native):tid=68 systid=6364 
       at libcore.io.Linux.access(Linux.java)
       at libcore.io.ForwardingOs.access(ForwardingOs.java:72)
       at libcore.io.BlockGuardOs.access(BlockGuardOs.java:73)
       at libcore.io.ForwardingOs.access(ForwardingOs.java:72)
       at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7587)
       at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
       at java.io.File.exists(File.java:815)
       at android.app.ContextImpl.ensureExternalDirsExistOrFilter(ContextImpl.java:2875)
       at android.app.ContextImpl.getExternalFilesDirs(ContextImpl.java:763)
       at android.app.ContextImpl.getExternalFilesDir(ContextImpl.java:752)
       at android.content.ContextWrapper.getExternalFilesDir(ContextWrapper.java:273)
       at com.mparticle.internal.MPUtility.getAvailableExternalDisk(SourceFile:1)
       at com.mparticle.internal.j.n(SourceFile:5)
       at com.mparticle.internal.i.a(SourceFile:364)
       at com.mparticle.b.handleMessage(SourceFile:17)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:368)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

```
main (blocked):tid=1 systid=5991 | waiting to lock <0x0c617f1e> (java.lang.Class<android.app.ContextImpl>) held by thread 77
       at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:469)
       at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:188)
       at com.braze.configuration.RuntimeAppConfigurationProvider.<init>(SourceFile:2)
       at com.braze.configuration.CachedConfigurationProvider.<init>(SourceFile:14)
       at com.braze.configuration.BrazeConfigurationProvider.<init>(SourceFile:1)
       at com.braze.ui.inappmessage.BrazeInAppMessageManager.registerInAppMessageManager(BrazeInAppMessageManager.java:189)
       at com.braze.BrazeActivityLifecycleCallbackListener.onActivityResumed(BrazeActivityLifecycleCallbackListener.kt:108)
       at android.app.Application.dispatchActivityResumed(Application.java:436)
       at android.app.Activity.dispatchActivityResumed(Activity.java:1379)
       at android.app.Activity.onResume(Activity.java:1905)
       at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:410)
```

I think it's basically complaining about accessing sharedPrefs on main thread.

**Comment by josh-bartz** [comment]
Getting a bunch of IO on main thread violations on startup. 8 of them, version 5.44.1:

```
StrictMode policy violation; ~duration=171 ms: android.os.strictmode.DiskReadViolation
                   at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1659)
                   at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
                   at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
                   at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7719)
                   at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
                   at java.io.File.exists(File.java:813)
                   at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:743)
                   at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:734)
                   at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:690)
                   at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:915)
                   at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:537)
                   at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:196)
                   at com.mparticle.internal.b.c(SourceFile:16)
                   at com.mparticle.internal.b.<init>(SourceFile:143)
                   at com.mparticle.internal.b.<init>(SourceFile:83)
                   at com.mparticle.MParticle.<init>(SourceFile:12)
                   at com.mparticle.MParticle.getInstance(SourceFile:14)
                   at com.mparticle.MParticle.start(SourceFile:1)
                   at com.onxmaps.onxmaps.ONXApplication.initializeMParticle(ONXApplication.kt:475)
                   at com.onxmaps.onxmaps.ONXApplication.onCreate(ONXApplication.kt:228)
                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6728)
                   at android.app.ActivityThread.access$1500(ActivityThread.java:247)
                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2057)
                   at android.os.Handler.dispatchMessage(Handler.java:106)
                   at android.os.Looper.loopOnce(Looper.java:201)
                   at android.os.Looper.loop(Looper.java:288)
                   at android.app.ActivityThread.main(ActivityThread.java:7842)
                   at java.lang.reflect.Method.invoke(Native Method)
                   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by ExpensiveBelly** [comment]
And another one:

```
mParticleMessageHandler (native):tid=71 systid=28495 
#00 pc 0xd7d88 libc.so (mkdirat + 8)
#01 pc 0x2176c libopenjdk.so (Java_java_io_UnixFileSystem_createDirectory0 + 92)
       at java.io.UnixFileSystem.createDirectory0(Native method)
       at java.io.UnixFileSystem.createDirectory(UnixFileSystem.java:354)
       at java.io.File.mkdir(File.java:1757)
       at java.io.File.mkdirs(File.java:1796)
       at android.app.ContextImpl.ensureExternalDirsExistOrFilter(ContextImpl.java:2950)
       at android.app.ContextImpl.getExternalFilesDirs(ContextImpl.java:788)
       at android.app.ContextImpl.getExternalFilesDir(ContextImpl.java:777)
       at android.content.ContextWrapper.getExternalFilesDir(ContextWrapper.java:273)
       at com.mparticle.internal.MPUtility.getAvailableExternalDisk(SourceFile:1)
       at com.mparticle.internal.j.n(SourceFile:5)
       at com.mparticle.internal.i.a(SourceFile:364)
       at com.mparticle.b.handleMessage(SourceFile:17)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:257)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

They are all related to accessing disk from main thread.

**Comment by ateek** [comment]
we are facing the same error when enabling StrictMode we are getting DiskReadViolation
```
               Caused by: android.os.strictmode.DiskReadViolation
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1658)
                                                                                                    	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
                                                                                                    	at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
                                                                                                    	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7749)
                                                                                                    	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
                                                                                                    	at java.io.File.exists(File.java:813)
                                                                                                    	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:759)
                                                                                                    	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:750)
                                                                                                    	at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:706)
                                                                                                    	at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:931)
                                                                                                    	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:553)
                                                                                                    	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:217)
                                                                                                    	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:217)
                                                                                                    	at com.mparticle.kits.KitIntegration.getKitPreferences(KitIntegration.java:232)
                                                                                                    	at com.mparticle.kits.AppboyKit.setAllUserAttributes(AppboyKit.kt:321)
                                                                                                    	at com.mparticle.kits.KitManagerImpl.onUserAttributesReceived(KitManagerImpl.java:589)
                                                                                                    	at com.mparticle.r0.a(SourceFile:24)
```

**Comment by ateek** [comment]
@samdozor any updates regarding that 🙏🏽

**Comment by samdozor** [comment]
Hi all - generally the SDK is meant to be called safely from the main thread.  Speaking to each of the above stack traces:

1. from @ExpensiveBelly `mParticleMessageHandler (native):tid=68 systid=6364 ` <- this is not on the main thread - so unsure why this would violate strict mode. the message handler is always on its own low priority thread.
2. from @ExpensiveBelly `main (blocked):tid=1 systid=5991 | waiting to lock <0x0c617f1e> (java.lang.Class<android.app.ContextImpl>) held by thread 77` <- this is the Braze SDK accessing sharedprefs (see below). we unfortunately have no control over how it accesses threads here, and in looking at the stack, it's seems required to happen from the main thread. I would recommend logging a bug with Braze for this one.
3. from @josh-bartz `at com.mparticle.MParticle.start(SourceFile:1)` this is an access of sharedprefs (see below)
4. from @ExpensiveBelly `#01 pc 0x2176c libopenjdk.so (Java_java_io_UnixFileSystem_createDirectory0 + 92)` <- this also is not on the main thread.
5. from @ExpensiveBelly `at com.mparticle.internal.MPUtility.getAvailableExternalDisk(SourceFile:1)` <- this is not on the main thread
6. from @ateek `at com.mparticle.kits.KitIntegration.getKitPreferences(KitIntegration.java:232)` <- this is a shared prefs read

For SharedPreferences reads (both in our SDK and in the Braze SDK) - it is a difficult challenge. In StrictMode's own documentation - they explicitly say that certain strict mode "violations" should not or cannot be fixed. It's regrettable that using SharedPrefs will hit disk the first time you call it - but SharedPreferences are cached in the first read of the process - so you would only get this violation once per app process, and the amount of "jank" it would provide the user experience should be quite minimal. In the mP SDK, it is important for example to know which kits must be started immediately, and to read settings immediately, to support initializing other SDKs as soon as possible. 

As the stacks above are all either not actually main thread or SharedPrefs call, I am going to close this issue for now. If you are seeing additional, non-sharedprefs-triggered strict mode violations, please open a new issue.
