### ISSUE TITLE
NullPointerException while trying to log Commerce Event

### ISSUE THREAD

**Issue by JanPawlov** [mParticle/mparticle-android-sdk#42]
I encountered an issue with logging Commerce Event when I updated mParticle dependency from version v5.9.2 to the latest release (v5.12.8).  Code related to event building has not changed:
```java
    @Override
    public void productListView(String storeName, List<WallStoreItem> items) {
        final Impression impression = new Impression(storeName, null);

        int position = 0;

        for (WallStoreItem item : items) {
            if (item instanceof ProductItem) {
                WallProduct wallProduct = ((ProductItem) item).getProduct();

                final Product.Builder productBuilder = new Product
                        .Builder(wallProduct.getName(), Long.toString(wallProduct.getId()), wallProduct.getPrice())
                        .quantity(1)
                        .position(++position);
                withPromotion(productBuilder, wallProduct.getPromotion());

                impression.addProduct(productBuilder.build());
            }
        }

        trackCommerceEvent(new CommerceEvent.Builder(impression));
    }

    protected void trackCommerceEvent(CommerceEvent.Builder eventBuilder) {

        final City city = hyperlocalService.city();
        final String currency = city != null ? city.getCurrency() : "";

        final Map<String, String> eventInfo = getCustomAttributesMap(eventBuilder);

        AsyncEventTrack.addGlobalProperties(eventInfo, hyperlocalService, mHyperlocalFiller,
                mUserId, dynamicSession.getSessionId(), cachedAttrs);

        eventBuilder
                .customAttributes(eventInfo)
                .currency(currency);
        MParticle.getInstance().logEvent(eventBuilder.build());
    }

```

Prior to the update, this event is successfully created and logged. After updating, 
```MParticle.getInstance().logEvent(eventBuilder.build());```
throws
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.mparticle.internal.b.d.<init>(SourceFile:24)
        at com.mparticle.internal.b.d$a.a(SourceFile:59)
        at com.mparticle.internal.u.a(SourceFile:367)
        at com.mparticle.MParticle.logCommerceEvent(SourceFile:404)
        at com.mparticle.MParticle.logEvent(SourceFile:351)
        at app.analytics.event.mparticle.MParticleEventTracker.trackCommerceEvent(MParticleEventTracker.java:289)
        at app.analytics.event.mparticle.MParticleEventTracker.productListView(MParticleEventTracker.java:1117)
        at app.wall.ui.temp.WallStoreListFragment.fireProductListViewAnalyticsEvent(WallStoreListFragment.java:486)
        at app.wall.ui.temp.WallStoreListFragment.lambda$onResume$4$WallStoreListFragment(WallStoreListFragment.java:442)
        at app.wall.ui.temp.-$$Lambda$WallStoreListFragment$ZoYTzLFys6UiJaHGcbplTp8wbJU.accept(Unknown Source:4)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:54)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

Looking at the [diff](https://github.com/mParticle/mparticle-android-sdk/compare/v5.9.2...v5.12.8) between two releases doesn't give me an answer on what might be wrong. 

I'm 99% sure `NPE` happens somewhere inside [this method](https://github.com/mParticle/mparticle-android-sdk/blob/c27efb89658e6db6be0318c0a05dfeaab8be21c0/android-core/src/main/java/com/mparticle/MParticle.java#L376) but I can't narrow it down because it's similiar to [v5.9.2](https://github.com/mParticle/mparticle-android-sdk/blob/776dc268695e6811ac4202fab420697745b0221e/android-core/src/main/java/com/mparticle/MParticle.java#L366).

Please note that every other Event used& tracked in the application is tracked properly

**Comment by JanPawlov** [comment]
It seems that as for the newest v5.12.9 release everything is working fine
