### ISSUE TITLE
Internal NullPointerException

### ISSUE THREAD

**Issue by romanYND** [mParticle/mparticle-android-sdk#50]
Hi, we have recently started to see the following stacktraces happening to our users:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mparticle.MParticle.disableLocationTracking()' on a null object reference
       at com.mparticle.internal.b.q(b.java:394)
       at com.mparticle.internal.b.h(b.java:380)
       at com.mparticle.internal.b$3.run(b.java:312)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8016)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```
As this seems internal we are not able to reproduce it, especially that we do not call `disableLocationTracking` at any time.
We're using version 5.14.4 of mParticle SDK

**Comment by willpassidomo** [comment]
Hello @romanYND this issue was resolved in version `5.14.6` of the MParticle SDK, in [this commit](https://github.com/mParticle/mparticle-android-sdk/commit/4b9e68d74eb3a18e30c0acf8c39147893f032933). More detailed explanation in the commit message, but the simplified version of the issue was that we call `disableLocationTracking()` when a Session ends just to make sure we are not tracking location in the background, regardless of whether it was enabled or not in the first place. This crash occurred when a session ended after the MParticle SDK had been shut down because we failed to check whether `MParticle.getInstance()` was present before trying to make this call
