### ISSUE TITLE
[Google Analytics KIT] getFirebaseInstanceId must not be called on the main application thread

### ISSUE THREAD

**Issue by extmkv** [mParticle/mparticle-android-sdk#52]
Hi mParticle team,

I'm always getting the following error when applying the `Google Firebase Kit` to my project.

`Exception while starting kit: Firebase not initialized. Check to make sure your google-services.json file is in the correct location`

After checking your logic I saw [you are ](https://github.com/mparticle-integrations/mparticle-android-integration-google-analytics-firebase/blob/cf82ecb1c421e8438d6aed7f116dcb00c9928be0/src/main/java/com/mparticle/kits/GoogleAnalyticsFirebaseKit.java#L53)calling the `getFirebaseInstanceId` inside of the Main Thread, based on Google Firebase documentation and my research that call will throw always the following exception:

`  java.lang.IllegalStateException: Must not be called on the main application thread
        at com.google.android.gms.common.internal.Preconditions.checkNotMainThread(com.google.android.gms:play-services-basement@@17.3.0:51)
        at com.google.android.gms.common.internal.Preconditions.checkNotMainThread(com.google.android.gms:play-services-basement@@17.3.0:48)
        at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@17.1.0:24)
        at com.google.firebase.analytics.FirebaseAnalytics.getFirebaseInstanceId(com.google.android.gms:play-services-measurement-api@@17.4.4:46)
        at com.XXX.XXX.XXX$onCreate$2$1.run(XXXXApp.kt:94)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
`

I tried to fetch `getFirebaseInstanceId` in my project inside a new thread and works.
`
  Thread(Runnable {
            FirebaseAnalytics.getInstance(context).firebaseInstanceId      
        }).start()
`

FYI I'm using Google Analytics Library Version: 17.4.4

**Comment by willpassidomo** [comment]
You are absolutely correct. I will get a fix out for this ASAP

**Comment by willpassidomo** [comment]
Thanks again for raising this issue, it has been fixed and shipped in version `5.14.10`
