### ISSUE TITLE
NullPointerException onInstallReferrerSetupFinished

### ISSUE THREAD

**Issue by ericntd** [mParticle/mparticle-android-sdk#53]
This is happening to a lot of our users and we don't know how to replicate
Our versions:
```
def mparticle = [
        appsflyer: "com.mparticle:android-appsflyer-kit:5.12.6",
        leanplum : "com.mparticle:android-leanplum-kit:5.12.6",
]

def appsflyer = [
        android:         "com.appsflyer:af-android-sdk:5.0.0",
        installreferrer: "com.android.installreferrer:installreferrer:1.0",
]
```

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       at android.os.Parcel.createException(Parcel.java:2077)
       at android.os.Parcel.readException(Parcel.java:2039)
       at android.os.Parcel.readException(Parcel.java:1987)
       at com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.getInstallReferrer(IGetInstallReferrerService.java:118)
       at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer(InstallReferrerClientImpl.java:187)
       at com.mparticle.b$1$1.onInstallReferrerSetupFinished(b.java:52)
       at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:222)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1948)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1980)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by willpassidomo** [comment]
Hey @ericntd thanks for reporting this issue. We have seen this problem pop up suddenly across a number of customer using the InstallReferrer v1.0 library. I looked into their sources and it seems like InstallReferrer is making a remote call and the data being returned can't be parsed into a `Parcel` which is resulting in an exception.

The best step you can do is to upgrade to the latest InstallReferrer dependency. In the meantime we are going to expand the `catch` block we wrap the call we make to `InstallReferrerClient.getInstallReferrer()` so this exception won't result in a crash. This will be released later today in version `5.14.7`

**Comment by Turnsole** [comment]
I'm also seeing it, also on v1.0 of InstallReferrer.

**Comment by willpassidomo** [comment]
The root issue in the InstallReferrer library remains something out of our control, in the meantime upgrading to version `5.14.8` or greater will prevent the exception from bubbling up and crashing an app
