### ISSUE TITLE
Failed mParticle action Identity Response: Identity Response Code: 400 Code: LOOKUP_ERROR Message: CleanCutStrategy login action is missing

### ISSUE THREAD

**Issue by ericntd** [mParticle/mparticle-android-sdk#65]
```
Non-fatal Exception: java.lang.Throwable: Failed mParticle action Identity Response:
Identity Response Code: 400
Code: LOOKUP_ERROR
Message: CleanCutStrategy login action is missing the login identity type.

       at com.myapp.feature.mparticle.MParticleManager.logFailure(MParticleManager.java:130)
       at com.myapp.feature.mparticle.MParticleManager.retryMParticleAction(MParticleManager.java:116)
       at com.myapp.feature.mparticle.MParticleManager.lambda$login$0(MParticleManager.java:38)
       at com.myapp.feature.mparticle.MParticleManager.lambda$hu2SJW-MyIgPnVY0aOSbGI_pCFI(MParticleManager.java)
       at com.myapp.feature.t.-$$Lambda$b$hu2SJW-MyIgPnVY0aOSbGI_pCFI.onFailure(-.java:2)
       at com.mparticle.identity.BaseIdentityTask$a.run(BaseIdentityTask.java:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8506)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

It started to surge around the time we release a version upgrading mParticle to `5.16.6`
```
def mparticle = [
        appsflyer: "com.mparticle:android-appsflyer-kit:5.16.6",
        leanplum : "com.mparticle:android-leanplum-kit:5.16.6",
]
```
Is there a cause and effect relationship here? 🙏

**Comment by willpassidomo** [comment]
Hey Eric, are you seeing that this message occurs only in 5.16.6, but not 5.16.5?

If now, this looks like an error message realating to your org's IDSync Identity Strategy. These are configured in the MParticle web dashboard, and some Identity Strategies impart additional requirements for type and contents of SDK-side identity requests. We aren't able to enforce these constraints client-side, so it is expected behavior that, if your request ran afoul of the strategy, we will trigger the onFailureListener callback with a 400 error

Sorry if this explanation is a little brief, additional information can be found [here in our docs](https://docs.mparticle.com/guides/idsync/introduction/)

**Comment by ericntd** [comment]
I looked further back and there was surge in earlier version too
Closing this for now, thanks @willpassidomo 
![Screen Shot 2021-05-27 at 10 46 16 AM](https://user-images.githubusercontent.com/19919208/119847325-e2aaf480-bed8-11eb-8a1c-1bb8a44efd38.png)
